# Generated by Django 4.1.5 on 2023-01-14 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0008_user_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('priority', models.CharField(max_length=200, null=True)),
                ('assignedUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bug_tracker.user')),
            ],
        ),
    ]
