# Generated by Django 4.1.5 on 2023-01-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0010_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
